
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox8;
	private global::Gtk.Alignment alignment6;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button button16;
	private global::Gtk.Alignment alignment8;
	private global::Gtk.Button button15;
	private global::Gtk.Alignment alignment9;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Button button18;
	private global::Gtk.Button button12;
	private global::Gtk.Alignment alignment12;
	private global::Gtk.Button button13;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Button button17;
	private global::Gtk.Alignment alignment11;
	private global::Gtk.Button button14;
	private global::Gtk.Alignment alignment10;
	private global::Gtk.Alignment alignment7;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CNC Controller");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 600;
		this.DefaultHeight = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment6.Name = "alignment6";
		this.vbox8.Add (this.alignment6);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.alignment6]));
		w1.Position = 0;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button16 = new global::Gtk.Button ();
		this.button16.CanFocus = true;
		this.button16.Name = "button16";
		this.button16.UseUnderline = true;
		this.button16.Label = global::Mono.Unix.Catalog.GetString ("+Z");
		this.hbox5.Add (this.button16);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button16]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment8.Name = "alignment8";
		this.hbox5.Add (this.alignment8);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment8]));
		w3.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button ();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString ("+Y");
		this.hbox5.Add (this.button15);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.button15]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment9.Name = "alignment9";
		this.hbox5.Add (this.alignment9);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.alignment9]));
		w5.Position = 3;
		this.vbox8.Add (this.hbox5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox5]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		w6.Padding = ((uint)(5));
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button18 = new global::Gtk.Button ();
		this.button18.CanFocus = true;
		this.button18.Name = "button18";
		this.button18.UseUnderline = true;
		this.button18.Label = global::Mono.Unix.Catalog.GetString ("Home");
		this.hbox6.Add (this.button18);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button18]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button12 = new global::Gtk.Button ();
		this.button12.CanFocus = true;
		this.button12.Name = "button12";
		this.button12.UseUnderline = true;
		this.button12.Label = global::Mono.Unix.Catalog.GetString ("-X");
		this.hbox6.Add (this.button12);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button12]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment12.Name = "alignment12";
		this.hbox6.Add (this.alignment12);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment12]));
		w9.Position = 2;
		// Container child hbox6.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button ();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString ("+X");
		this.hbox6.Add (this.button13);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button13]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		w11.Padding = ((uint)(5));
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button17 = new global::Gtk.Button ();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString ("-Z");
		this.hbox7.Add (this.button17);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button17]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment11.Name = "alignment11";
		this.hbox7.Add (this.alignment11);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment11]));
		w13.Position = 1;
		// Container child hbox7.Gtk.Box+BoxChild
		this.button14 = new global::Gtk.Button ();
		this.button14.CanFocus = true;
		this.button14.Name = "button14";
		this.button14.UseUnderline = true;
		this.button14.Label = global::Mono.Unix.Catalog.GetString ("-Y");
		this.hbox7.Add (this.button14);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button14]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment10.Name = "alignment10";
		this.hbox7.Add (this.alignment10);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment10]));
		w15.Position = 3;
		this.vbox8.Add (this.hbox7);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox7]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		w16.Padding = ((uint)(5));
		// Container child vbox8.Gtk.Box+BoxChild
		this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment7.Name = "alignment7";
		this.vbox8.Add (this.alignment7);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.alignment7]));
		w17.PackType = ((global::Gtk.PackType)(1));
		w17.Position = 5;
		this.Add (this.vbox8);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
